<a href="https://colab.research.google.com/github/bioduds/ALGORITMOS-UFMG/blob/main/Experimentos_com_Python_e_R_hibrido.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Usando Python e R de forma híbrida (alguns exemplos com Álgebra Linear)
---

**Author:** Eduardo Capanema


In [1]:
# ativamos R magic para usar R e Python de forma híbrida
%load_ext rpy2.ipython

/usr/local/lib/python3.6/dist-packages/rpy2/robjects/pandas2ri.py:14: FutureWarning: pandas.core.index is deprecated and will be removed in a future version.  The public classes are available in the top-level namespace.
  from pandas.core.index import Index as PandasIndex
/usr/local/lib/python3.6/dist-packages/rpy2/robjects/pandas2ri.py:34: UserWarning: pandas >= 1.0 is not supported.
  warnings.warn('pandas >= 1.0 is not supported.')


In [ ]:
import pandas as pd
import numpy as np

Usamos código R utilizando %%R como abaixo

In [2]:
%%R

x <- 42
print( x )

[1] 42


In [17]:
%%R 

soma <- function( v1, v2 ) {
    return ( v1 + v2 )
}


Usamos %R -o para chamar a função de R e carregar em uma variável no Python

In [78]:
%R -o S S=soma( 1, 2 )
print( "Beleza ", S )
type( S )

Beleza  [3.]


numpy.ndarray

Usamos %Rpush para carregar uma variável de Python dentro do R


In [38]:
X = np.array( [ 4.5, 6.3, 7.9] )
X.mean()

%Rpush X


In [39]:
%%R 
print( X )

[1] 4.5 6.3 7.9


E usamos %R -o para carregar uma variável de R dentro do Python

In [86]:
%%R

D <- c( 2, 3, 4.5 )
D
tr <- t(D)
print( tr )

     [,1] [,2] [,3]
[1,]    2    3  4.5


In [68]:
%R -o D

print( D )
type( D )

[2.  3.  4.5]


numpy.ndarray

Experimentemos uma matriz em R

In [72]:
%%R

M <- matrix( c( 1, 3, 4, 5, 4, 3 ) )


Vamos tentar puxar essa matriz para python


In [74]:
%R -o M

M

array([[1.],
       [3.],
       [4.],
       [5.],
       [4.],
       [3.]])

Vamos tentar o contrário, criar uma matriz numpy e mandar pro R

In [76]:
Matrix = np.array( [ [3, 5, 8], [0, 2, 2], [9, 14, 2] ])
%Rpush Matrix


In [80]:
%%R
print( Matrix )

     [,1] [,2] [,3]
[1,]    3    5    8
[2,]    0    2    2
[3,]    9   14    2


Vamos transpor a matriz e retornar pro Python


In [88]:
%%R
trMatrix = t( Matrix )
print( trMatrix )

     [,1] [,2] [,3]
[1,]    3    0    9
[2,]    5    2   14
[3,]    8    2    2


In [90]:
%R -o trMatrix

trMatrix

array([[ 3,  0,  9],
       [ 5,  2, 14],
       [ 8,  2,  2]], dtype=int32)

Agora vamos comparar a solução de um sistema linear em R e em Python:

In [103]:
%%R

A <- matrix( c( 1, 2, 3, 4 ), ncol = 2 )
b <- c( 7, 10 )
x <- solve( A ) %*% b
print( x )

     [,1]
[1,]    1
[2,]    2


In [104]:
A = np.array( [ [1, 3], [2, 4] ])
b = np.array( [ [7], [10] ] )
x = np.linalg.inv( A ) @ b
print( x )

[[1.]
 [2.]]
